# Generated by Django 2.2.24 on 2021-09-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.PositiveSmallIntegerField()),
                ('happy', models.BooleanField()),
                ('healthy', models.BooleanField()),
                ('busy', models.BooleanField()),
            ],
        ),
    ]
